# Piston Launcher Settings
last_server: "Hypixel"
servers:
  Hypixel:
    ip: "ClawedMists-sG60.aternos.me"
    port: 56350
  Mineplex:
    ip: "us.mineplex.com"
    port: 25565
  MyPrivateServer:
    ip: "123.456.7.8"
    port: 25565